import { NASA93Input } from '../types';

export const INITIAL_FORM_STATE: NASA93Input = {
  projectname: 'HST',
  cat2: 'scientific',
  forg: 'g',
  center: 2,
  year: 1993,
  mode: 'semidetached',
  equivphyskloc: 48.5,
  rely: 'h',
  data: 'n',
  cplx: 'h',
  time: 'h',
  stor: 'n',
  virt: 'n',
  turn: 'n',
  acap: 'h',
  aexp: 'h',
  pcap: 'h',
  vexp: 'n',
  lexp: 'n',
  modp: 'h',
  tool: 'h',
  sced: 'n',
};

export const NASA93_METADATA = {
  projectname: {
    label: 'Project Name / ID',
    labelAr: 'اسم / معرّف المشروع',
    options: ['HST', 'SLP', 'GAL', 'DE', 'ERB', 'X', 'SPL', 'SYS', 'SAT', 'SIM', 'ENG'],
  },
  cat2: {
    label: 'Domain Category',
    labelAr: 'فئة المجال التطبيقي',
    options: [
      { v: 'avionics', l: 'Avionics (إلكترونيات الطيران)' },
      { v: 'command_control', l: 'Command & Control (القيادة والسيطرة)' },
      { v: 'data_management', l: 'Data Management (إدارة البيانات)' },
      { v: 'flight_combined', l: 'Flight Combined (أنظمة الطيران المدمجة)' },
      { v: 'ground_combined', l: 'Ground Combined (الأنظمة الأرضية)' },
      { v: 'launch_processing', l: 'Launch Processing (معالجة الإطلاق)' },
      { v: 'mission_planning', l: 'Mission Planning (تخطيط المهام)' },
      { v: 'operating_system', l: 'Operating System (أنظمة التشغيل)' },
      { v: 'real_time_control', l: 'Real-Time Control (التحكم الآني)' },
      { v: 'scientific', l: 'Scientific & Instruments (علمي ومعالجة بيانات)' },
      { v: 'simulation', l: 'Simulation & Training (المحاكاة)' },
      { v: 'utility', l: 'Utility & Tools (الأدوات المساعدة)' },
    ],
  },
  forg: {
    label: 'Organization',
    labelAr: 'نوع المؤسسة',
    options: [
      { v: 'g', l: 'Government / In-House (حكومي)' },
      { v: 'f', l: 'Facility / Contractor (منشأة / مقاول)' },
    ],
  },
  center: {
    label: 'NASA Center',
    labelAr: 'مركز ناسا',
    options: [
      { v: 1, l: 'Center 1 (GSFC - Goddard Space Flight Center)' },
      { v: 2, l: 'Center 2 (JPL - Jet Propulsion Laboratory)' },
      { v: 3, l: 'Center 3 (JSC - Johnson Space Center)' },
      { v: 5, l: 'Center 5 (KSC - Kennedy Space Center)' },
      { v: 6, l: 'Center 6 (MSFC - Marshall Space Flight Center)' },
    ],
  },
  mode: {
    label: 'Development Mode',
    labelAr: 'نمط التطوير',
    options: [
      { v: 'organic', l: 'Organic (عضوي - مرن وصغير)' },
      { v: 'semidetached', l: 'Semi-Detached (شبه منفصل - متوسط)' },
      { v: 'embedded', l: 'Embedded (مدمج - قيود حرجة وصارمة)' },
    ],
  },
  costDriverLevels: [
    { v: 'vl', num: 1, l: 'Very Low (منخفض جداً)', short: 'VL' },
    { v: 'l', num: 2, l: 'Low (منخفض)', short: 'L' },
    { v: 'n', num: 3, l: 'Nominal (طبيعي)', short: 'N' },
    { v: 'h', num: 4, l: 'High (عالي)', short: 'H' },
    { v: 'vh', num: 5, l: 'Very High (عالي جداً)', short: 'VH' },
    { v: 'xh', num: 6, l: 'Extra High (فائق)', short: 'XH' },
  ],
  driverWeights: {
    rely: { vl: 0.75, l: 0.88, n: 1.0, h: 1.15, vh: 1.40, xh: 1.40 },
    data: { vl: 0.94, l: 0.94, n: 1.0, h: 1.08, vh: 1.16, xh: 1.16 },
    cplx: { vl: 0.70, l: 0.85, n: 1.0, h: 1.15, vh: 1.30, xh: 1.65 },
    time: { vl: 1.00, l: 1.00, n: 1.0, h: 1.11, vh: 1.30, xh: 1.66 },
    stor: { vl: 1.00, l: 1.00, n: 1.0, h: 1.06, vh: 1.21, xh: 1.56 },
    virt: { vl: 0.87, l: 0.87, n: 1.0, h: 1.15, vh: 1.30, xh: 1.30 },
    turn: { vl: 0.87, l: 0.87, n: 1.0, h: 1.07, vh: 1.15, xh: 1.15 },
    acap: { vl: 1.46, l: 1.19, n: 1.0, h: 0.86, vh: 0.71, xh: 0.71 },
    aexp: { vl: 1.29, l: 1.13, n: 1.0, h: 0.91, vh: 0.82, xh: 0.82 },
    pcap: { vl: 1.42, l: 1.17, n: 1.0, h: 0.86, vh: 0.70, xh: 0.70 },
    vexp: { vl: 1.21, l: 1.10, n: 1.0, h: 0.90, vh: 0.90, xh: 0.90 },
    lexp: { vl: 1.14, l: 1.07, n: 1.0, h: 0.95, vh: 0.95, xh: 0.95 },
    modp: { vl: 1.24, l: 1.10, n: 1.0, h: 0.91, vh: 0.82, xh: 0.82 },
    tool: { vl: 1.24, l: 1.10, n: 1.0, h: 0.91, vh: 0.83, xh: 0.83 },
    sced: { vl: 1.23, l: 1.08, n: 1.0, h: 1.04, vh: 1.10, xh: 1.10 },
  } as Record<string, Record<string, number>>,
  costDrivers: {
    rely: { code: 'RELY', label: 'Required Software Reliability', labelAr: 'الاعتمادية المطلوبة للبرمجيات', info: 'Consequence of software failure (low to life-critical).', infoAr: 'عواقب توقف أو فشل البرمجيات.', category: 'product' },
    data: { code: 'DATA', label: 'Database Size Constraint', labelAr: 'حجم قواعد البيانات الملحقة', info: 'Database bytes to source code ratio.', infoAr: 'نسبة حجم البيانات إلى أسطر الكود البرمجي.', category: 'product' },
    cplx: { code: 'CPLX', label: 'Product & Algorithmic Complexity', labelAr: 'التعقيد الخوارزمي والعملياتي', info: 'Computational, control logic and math complexity.', infoAr: 'درجة تعقيد العمليات الحسابية ومنطق التحكم.', category: 'product' },
    time: { code: 'TIME', label: 'Execution Time Constraint', labelAr: 'قيود وقت التنفيذ (المعالج)', info: 'Percentage of available CPU execution used.', infoAr: 'نسبة استهلاك دورات المعالج المتاحة.', category: 'computer' },
    stor: { code: 'STOR', label: 'Main Storage Constraint', labelAr: 'قيود الذاكرة الرئيسية (RAM)', info: 'Percentage of RAM/storage utilized.', infoAr: 'نسبة استهلاك الذاكرة الرئيسية المستهدفة.', category: 'computer' },
    virt: { code: 'VIRT', label: 'Virtual Machine Volatility', labelAr: 'تقلب بيئة التشغيل والعتاد', info: 'Frequency of hardware/OS updates during dev.', infoAr: 'معدل التغييرات في العتاد والأنظمة.', category: 'computer' },
    turn: { code: 'TURN', label: 'Computer Turnaround Time', labelAr: 'زمن استجابة بيئة التطوير', info: 'Turnaround duration for builds and tests.', infoAr: 'الزمن اللازم للحصول على نتائج البناء.', category: 'computer' },
    acap: { code: 'ACAP', label: 'Analyst Capability', labelAr: 'كفاءة محلل النظم', info: 'Capability and efficiency of system analysts.', infoAr: 'كفاءة وخبرة محللي النظم.', category: 'personnel' },
    aexp: { code: 'AEXP', label: 'Applications Experience', labelAr: 'خبرة الفريق في المجال التطبيقي', info: 'Years of team experience with similar systems.', infoAr: 'عدد سنوات خبرة الفريق في نفس المجال.', category: 'personnel' },
    pcap: { code: 'PCAP', label: 'Programmer Capability', labelAr: 'كفاءة المبرمجين والمطورين', info: 'Coding ability, quality and team efficiency.', infoAr: 'مستوى مهارات المبرمجين.', category: 'personnel' },
    vexp: { code: 'VEXP', label: 'Virtual Machine Experience', labelAr: 'خبرة بيئة التشغيل والأنظمة', info: 'Team experience with target OS and hardware.', infoAr: 'مدى إلمام الفريق بالبيئة ونظام التشغيل.', category: 'personnel' },
    lexp: { code: 'LEXP', label: 'Programming Language Experience', labelAr: 'الخبرة بلغة البرمجة المستخدمة', info: 'Familiarity with selected programming language.', infoAr: 'مدى تمكن الفريق من لغة البرمجة.', category: 'personnel' },
    modp: { code: 'MODP', label: 'Modern Programming Practices', labelAr: 'استخدام الممارسات الحديثة', info: 'Use of modular design, code review and CI.', infoAr: 'تطبيق أساليب التصميم المنظم والمراجعات.', category: 'project' },
    tool: { code: 'TOOL', label: 'Use of Software Engineering Tools', labelAr: 'استخدام أدوات هندسة البرمجيات', info: 'Integration of static analyzers, debuggers, IDEs.', infoAr: 'استخدام أدوات التحليل الآلي والتطوير.', category: 'project' },
    sced: { code: 'SCED', label: 'Required Development Schedule', labelAr: 'ضغط الجدول الزمني المطلوب', info: 'Degree of schedule compression or stretch.', infoAr: 'مدى ضغط أو تمديد الجدول الزمني.', category: 'project' },
  },
};
